// 4.1 케이스 레지스트리 — 문서 케이스 ID ↔ 자동 테스트 구현 매핑(리포트 생성기 공유).
// AUTOMATED: 자동 테스트가 존재하는 케이스(테스트 title 접두에 해당 ID). 결과 미수집 시 skip(미실행).
// MANUAL: 자동화 불가/미대상 — 리포트에서 manual 로 집계(note 표기).

export const AUTOMATED = {
  // PRD v3 공개 사이트 acceptance (public/public.spec.ts)
  "PUB-001": { kind: "e2e", spec: "public/public" },
  "PUB-002": { kind: "e2e", spec: "public/public" },
  "PUB-003": { kind: "e2e", spec: "public/public" },
  "PUB-004": { kind: "e2e+static", spec: "public/public" },
  "PUB-005": { kind: "e2e", spec: "public/public" },
  "PUB-006": { kind: "e2e", spec: "public/public" },
  "APP-001": { kind: "e2e", spec: "public/application" },
  "APP-002": { kind: "e2e", spec: "public/application" },
  "APP-003": { kind: "e2e", spec: "public/application" },
  "APP-004": { kind: "e2e+db", spec: "public/application" },
  "APP-005": { kind: "e2e", spec: "public/application" },
  "APP-006": { kind: "contract+db", spec: "public/application" },
  "APP-007": { kind: "e2e+db", spec: "public/application" },
  "APP-008": { kind: "e2e+db", spec: "public/application" },
  "APP-009": { kind: "e2e+api", spec: "public/application" },
  "APP-010": { kind: "e2e+api", spec: "public/application" },
  "APP-011": { kind: "e2e+api", spec: "public/application" },
  "APP-012": { kind: "e2e", spec: "public/application" },
  "APP-013": { kind: "e2e", spec: "public/application" },
  "APP-014": { kind: "api", spec: "public/application" },
  "ACC-001": { kind: "e2e", spec: "public/access" },
  "ACC-002": { kind: "e2e", spec: "public/access" },
  "ACC-003": { kind: "e2e", spec: "public/access" },
  "ACC-004": { kind: "e2e", spec: "public/access" },
  "ACC-005": { kind: "e2e", spec: "public/access" },
  "ACC-006": { kind: "e2e", spec: "public/access" },
  "ACC-007": { kind: "e2e+api", spec: "public/access" },
  "ACC-008": { kind: "e2e", spec: "public/access" },
  "ACC-009": { kind: "e2e", spec: "public/access" },
  "ACC-010": { kind: "e2e+db", spec: "transitions" },
  "ACC-011": { kind: "e2e+db", spec: "transitions" },
  "ACC-012": { kind: "e2e+db", spec: "transitions" },
  "ACC-013": { kind: "e2e", spec: "public/access" },
  "ACC-014": { kind: "e2e", spec: "public/access" },
  "AUTH-001": { kind: "e2e", spec: "public/auth" },
  "AUTH-002": { kind: "e2e", spec: "public/auth" },
  "AUTH-003": { kind: "e2e", spec: "public/auth" },
  "AUTH-004": { kind: "contract+e2e", spec: "public/auth" },
  "AUTH-005": { kind: "e2e+db", spec: "public/auth" },
  "AUTH-006": { kind: "e2e+db", spec: "public/auth" },
  "AUTH-007": { kind: "e2e", spec: "public/auth" },
  "AUTH-008": { kind: "e2e", spec: "public/auth" },
  "AUTH-009": { kind: "e2e", spec: "public/auth" },
  "AUTH-010": { kind: "db+api", spec: "public/auth" },
  "AUTH-011": { kind: "e2e", spec: "public/auth" },
  "AUTH-012": { kind: "contract", spec: "public/auth" },
  "AUTH-013": { kind: "e2e", spec: "public/auth" },
  "AUTH-014": { kind: "e2e", spec: "public/auth" },
  "ENR-001": { kind: "e2e+db", spec: "public/billing" },
  "ENR-002": { kind: "contract+db", spec: "public/billing" },
  "ENR-003": { kind: "e2e+db", spec: "public/billing" },
  "ENR-004": { kind: "api+db", spec: "public/billing" },
  "BILL-001": { kind: "e2e+db", spec: "public/billing" },
  "BILL-002": { kind: "e2e", spec: "public/billing" },
  "BILL-003": { kind: "e2e", spec: "public/billing" },
  "BILL-004": { kind: "e2e+db", spec: "public/billing" },
  "BILL-005": { kind: "e2e+db+contract", spec: "public/billing" },
  "BILL-006": { kind: "api+db", spec: "public/billing" },
  "BILL-007": { kind: "contract+api", spec: "public/billing" },
  "BILL-008": { kind: "api", spec: "public/billing" },
  "BILL-009": { kind: "contract+db", spec: "public/billing" },
  "BILL-010": { kind: "contract+db", spec: "public/billing" },
  "BILL-011": { kind: "e2e+db", spec: "public/billing" },
  "BILL-012": { kind: "api+e2e", spec: "public/billing" },
  "BILL-013": { kind: "api+db", spec: "public/billing" },
  "MEM-001": { kind: "e2e+db", spec: "public/billing" },
  "MEM-002": { kind: "e2e", spec: "public/billing" },
  "LMS-001": { kind: "e2e", spec: "public/lms" },
  "LMS-002": { kind: "e2e+db", spec: "public/lms" },
  "LMS-003": { kind: "e2e", spec: "public/lms" },
  "LMS-004": { kind: "e2e", spec: "public/lms" },
  "LMS-005": { kind: "e2e", spec: "public/lms" },
  "LMS-006": { kind: "e2e", spec: "public/lms" },
  "LMS-007": { kind: "e2e", spec: "public/lms" },
  "LMS-008": { kind: "e2e+db", spec: "public/lms" },
  "LMS-009": { kind: "api", spec: "public/lms" },
  "LMS-010": { kind: "e2e+db", spec: "public/lms" },
  "LMS-011": { kind: "contract", spec: "public/lms" },
  "LMS-012": { kind: "e2e+contract", spec: "public/lms" },
  "LMS-013": { kind: "e2e+db", spec: "public/lms" },
  "LMS-014": { kind: "contract+api", spec: "public/lms" },
  "LMS-018": { kind: "e2e+db", spec: "public/lms" },
  "LMS-019": { kind: "e2e+db", spec: "public/lms" },
  "LMS-020": { kind: "api", spec: "public/lms" },
  "LMS-021": { kind: "e2e+db", spec: "public/lms" },
  "LMS-022": { kind: "e2e+db", spec: "public/lms" },
  "LMS-024": { kind: "contract+db", spec: "public/lms" },
  "AI-003": { kind: "e2e+api", spec: "public/ai" },
  "AI-004": { kind: "e2e", spec: "public/ai" },
  "AI-005": { kind: "e2e", spec: "public/ai" },
  "AI-006": { kind: "e2e", spec: "public/ai" },
  "AI-007": { kind: "api+db", spec: "public/ai" },
  "AI-008": { kind: "api", spec: "public/ai" },
  "AI-009": { kind: "api", spec: "public/ai" },
  "AI-010": { kind: "e2e+db", spec: "public/ai" },
  "AI-011": { kind: "e2e", spec: "public/ai" },
  "AI-012": { kind: "e2e+db", spec: "public/ai" },
  "AI-013": { kind: "e2e", spec: "public/ai" },
  "TASK-001": { kind: "e2e+db", spec: "public/workflows" }, "TASK-002": { kind: "e2e+db", spec: "public/workflows" },
  "TASK-003": { kind: "api", spec: "public/workflows" }, "TASK-004": { kind: "e2e", spec: "public/workflows" },
  "BUILD-001": { kind: "e2e+db", spec: "public/workflows" }, "BUILD-002": { kind: "e2e+db", spec: "public/workflows" },
  "BUILD-003": { kind: "e2e+db", spec: "public/workflows" }, "BUILD-004": { kind: "e2e+db", spec: "public/workflows" },
  "BUILD-005": { kind: "api", spec: "public/workflows" },
  "ROAD-001": { kind: "e2e+db", spec: "public/workflows" }, "ROAD-002": { kind: "e2e+db", spec: "public/workflows" },
  "ROAD-003": { kind: "e2e+db", spec: "public/workflows" }, "ROAD-004": { kind: "api", spec: "public/workflows" },
  "ARCH-001": { kind: "e2e+db", spec: "public/workflows" }, "ARCH-002": { kind: "e2e", spec: "public/workflows" },
  "ARCH-003": { kind: "e2e+db", spec: "public/workflows" }, "ARCH-004": { kind: "api", spec: "public/workflows" },
  "ADM-001": { kind: "e2e+db", spec: "public/admin" }, "ADM-002": { kind: "e2e+db", spec: "public/admin" },
  "ADM-003": { kind: "e2e+db", spec: "public/admin" }, "ADM-004": { kind: "contract+db", spec: "public/admin" },
  "ADM-005": { kind: "e2e+db", spec: "public/lms" }, "ADM-006": { kind: "e2e+db", spec: "public/lms" },
  "ADM-007": { kind: "e2e+db", spec: "public/admin" }, "ADM-008": { kind: "e2e", spec: "public/admin" },
  "ADM-009": { kind: "e2e+db", spec: "public/admin" }, "ADM-010": { kind: "e2e+db", spec: "public/billing" },
  "ADM-011": { kind: "e2e+db", spec: "public/admin" }, "ADM-012": { kind: "e2e+db", spec: "public/ai" },
  "ADM-013": { kind: "e2e+db", spec: "public/admin" }, "ADM-014": { kind: "e2e+db", spec: "public/admin" },
  "ADM-015": { kind: "contract", spec: "public/admin" }, "ADM-016": { kind: "e2e", spec: "public/admin" },
  "SEC-001": { kind: "static+db", spec: "public/security-nfr" }, "SEC-002": { kind: "api", spec: "public/security-nfr" },
  "SEC-006": { kind: "api", spec: "public/security-nfr" }, "SEC-007": { kind: "api", spec: "public/security-nfr" },
  "SEC-010": { kind: "api", spec: "public/security-nfr" }, "SEC-011": { kind: "api", spec: "public/security-nfr" },
  "SEC-012": { kind: "static+e2e", spec: "public/security-nfr" }, "SEC-013": { kind: "api", spec: "public/security-nfr" },
  "SEC-014": { kind: "e2e+static", spec: "public/security-nfr" },
  "NFR-001": { kind: "e2e", spec: "public/security-nfr" }, "NFR-002": { kind: "e2e", spec: "public/security-nfr" },
  "NFR-003": { kind: "static+e2e", spec: "public/security-nfr" }, "NFR-004": { kind: "e2e", spec: "public/security-nfr" },
  "NFR-005": { kind: "e2e", spec: "public/security-nfr" }, "NFR-006": { kind: "e2e+static", spec: "public/security-nfr" },
  "NFR-007": { kind: "e2e+static", spec: "public/security-nfr" }, "NFR-008": { kind: "static", spec: "public/security-nfr" },
  "LMS-015": { kind: "e2e+db", spec: "actions" },
  "LMS-016": { kind: "api", spec: "rls" },
  "LMS-017": { kind: "e2e+db", spec: "actions" },
  "LMS-023": { kind: "e2e+db", spec: "actions" },
  "AI-001": { kind: "api", spec: "api.authz" },
  "AI-002": { kind: "rag", spec: "rag.smoke" },
  "AI-014": { kind: "api+static", spec: "rls" },
  "SEC-003": { kind: "api", spec: "rls" },
  "SEC-004": { kind: "api", spec: "rls" },
  "SEC-005": { kind: "api", spec: "rls" },
  "SEC-008": { kind: "api", spec: "api.authz" },
  "SEC-009": { kind: "api", spec: "rls" },
  "MEM-003": { kind: "api+db", spec: "rls" },

  // 접근 매트릭스 E2E (matrix.access.spec.ts)
  "AC-01": { kind: "e2e", spec: "matrix" }, "AC-02": { kind: "e2e", spec: "matrix" },
  "AC-03": { kind: "e2e", spec: "matrix" }, "AC-04": { kind: "e2e", spec: "matrix" },
  "AC-05": { kind: "e2e", spec: "matrix" }, "AC-06": { kind: "e2e", spec: "matrix" },
  "AC-07": { kind: "e2e", spec: "matrix" }, "AC-08": { kind: "e2e", spec: "matrix" },
  "AC-09": { kind: "e2e", spec: "matrix" }, "AC-10": { kind: "e2e", spec: "matrix" },
  "AC-11": { kind: "e2e", spec: "matrix" }, "AC-12": { kind: "e2e", spec: "matrix" },
  "AC-13": { kind: "e2e", spec: "matrix" },
  "AC-14": { kind: "e2e", spec: "matrix" }, "AC-16": { kind: "e2e", spec: "matrix" },
  "AC-17": { kind: "e2e", spec: "matrix" }, "AC-19": { kind: "e2e", spec: "matrix" },
  "AC-20": { kind: "e2e", spec: "matrix" }, "AC-21": { kind: "e2e", spec: "matrix" },
  "AC-23": { kind: "e2e", spec: "matrix" }, "AC-25": { kind: "e2e", spec: "matrix" },
  "AC-26": { kind: "e2e", spec: "matrix" }, "AC-27": { kind: "e2e", spec: "matrix" },
  "AC-28": { kind: "e2e", spec: "matrix" }, "AC-30": { kind: "e2e", spec: "matrix" },
  "AC-31": { kind: "e2e", spec: "matrix" },
  // 08 영상/자료 권한 셀 (matrix.access.spec.ts — sessionDetail DOM 마커/리다이렉트)
  "LMS-V09": { kind: "e2e", spec: "matrix" },
  "LMS-V10": { kind: "e2e", spec: "matrix" },
  "LMS-M04": { kind: "e2e", spec: "matrix" },

  // 상태 전이 픽스처 (transitions.spec.ts — setup 변형 → 접근 → 원복)
  "AC-32": { kind: "e2e", spec: "transitions" },
  "AC-33": { kind: "e2e", spec: "transitions" },
  "AC-34": { kind: "e2e", spec: "transitions" },

  // API 인가 (api.authz.spec.ts)
  "AI-01": { kind: "api", spec: "api.authz" },
  "LMS-AI04": { kind: "api", spec: "api.authz" },
  "SEC-10": { kind: "api", spec: "api.authz" },

  // RLS (rls.security.spec.ts)
  "SEC-01": { kind: "rls", spec: "rls" }, "SEC-02": { kind: "rls", spec: "rls" },
  "SEC-03": { kind: "rls", spec: "rls" }, "SEC-05": { kind: "rls", spec: "rls" },
  "SEC-06": { kind: "rls", spec: "rls" }, "SEC-08": { kind: "rls", spec: "rls" },
  "SEC-09": { kind: "rls", spec: "rls" }, "SEC-12": { kind: "rls", spec: "rls" },
  "AI-15": { kind: "rls", spec: "rls" },
  "LMS-Q05": { kind: "rls", spec: "rls" }, "LMS-A06": { kind: "rls", spec: "rls" },
  "LMS-ADM07": { kind: "rls", spec: "rls" },

  // 서버액션 · LMS DB 반영 (actions.lms.spec.ts)
  "LMS-Q01": { kind: "action+db", spec: "actions" },
  "LMS-Q04": { kind: "action+db", spec: "actions" },
  "LMS-A02": { kind: "action+db", spec: "actions" },
  "LMS-A03": { kind: "action+db", spec: "actions" },
  "ADM-14": { kind: "action+db", spec: "actions" },
  "ADM-15": { kind: "action+db", spec: "actions" },
  "LMS-ADM01": { kind: "action+db", spec: "actions" },
  "LMS-ADM04": { kind: "action+db", spec: "actions" },
  "LMS-ADM05": { kind: "action+db", spec: "actions" },
  "ADM-10": { kind: "action+db", spec: "actions" },
  "ADM-16": { kind: "action+db", spec: "actions" },

  // 정적 게이트 (gate-lint.mjs)
  "SEC-11": { kind: "static", spec: "gate-lint" },

  // RAG 스모크 (rag.smoke.spec.ts)
  "AI-02": { kind: "rag", spec: "rag.smoke" },
};

export const MANUAL = {
  "NFR-009": "승인된 desktop/mobile visual baseline과 0.5% diff 승인 절차가 필요",
  "NFR-010": "backup-enabled 별도 staging에서 PITR restore drill과 증거 기록이 필요",
  "LMS-V05": "YouTube seek 실클릭 — cross-origin postMessage, 스모크/수동만",
  "LMS-V06": "mp4 seek 실클릭 — 수동 확인",
  "LMS-AI02": "출처 타임스탬프 칩 클릭 seek — LMS-V05 와 동일 경로(수동)",
  "AUTH-04": "매직링크 메일 수신 필요 — 수동/Admin API generateLink 우회",
  "AUTH-05": "최초 매직링크 → set-password 강제 — 수동",
  "AC-40": "모바일 하단 탭 노출 — 시각 확인(수동)",
  "AC-41": "졸업생 모바일 탭 UX 갭 — 수동",
};

// title 문자열에서 모든 케이스 ID 토큰 추출(예: "LMS-Q01/Q04" → ["LMS-Q01","LMS-Q04"])
export function extractCaseIds(title) {
  const ids = new Set();
  const re = /\b([A-Z]{2,5}-[A-Z]{0,4}\d{1,3})\b/g;
  let m;
  while ((m = re.exec(title))) ids.add(m[1]);
  return [...ids];
}
