import { expect, test, type Browser } from "@playwright/test";
import { admin, assertMutationTarget, userId } from "../lib/supa.mjs";
import { ensureStorageState } from "../fixtures/accounts";
const COHORT="00000000-0000-0000-0000-0000000000c1";
async function adminCtx(browser:Browser){return browser.newContext({storageState:await ensureStorageState(browser,"admin")});}
async function seedSession(title:string,sort_order:number){const r=await admin().from("sessions").insert({cohort_id:COHORT,week_no:80,title,type:"special",starts_at:"2026-08-01T01:00:00Z",ends_at:"2026-08-01T04:00:00Z",sort_order,is_published:true}).select("*").single();if(r.error)throw r.error;return r.data;}
async function cleanSession(id:string){await admin().from("videos").delete().eq("session_id",id);await admin().from("materials").delete().eq("session_id",id);await admin().from("curriculum_change_logs").delete().eq("entity_id",id);await admin().from("sessions").delete().eq("id",id);}

test.describe("admin console acceptance",()=>{
 test("ADM-001 KPI DB count 일치·대표값 하드코딩 금지",async({browser})=>{const apps=(await admin().from("applications").select("id",{count:"exact",head:true})).count??0;const paid=(await admin().from("invoices").select("id",{count:"exact",head:true}).eq("status","paid")).count??0;const c=await adminCtx(browser);try{const p=await c.newPage();await p.goto("/admin",{waitUntil:"networkidle"});const appCard=p.locator("div.rounded-\\[15px\\]",{hasText:"지원자"}).first(),paidCard=p.locator("div.rounded-\\[15px\\]",{hasText:"입금 완료"}).first();await expect(appCard).toContainText(String(apps));await expect(paidCard).toContainText(String(paid));await expect(p.getByText("64%",{exact:true})).toHaveCount(0);await expect(p.getByText("78%",{exact:true})).toHaveCount(0);await expect(p.getByText("42",{exact:true})).toHaveCount(0);}finally{await c.close();}});
 test("ADM-002 지원자 이름·회사 검색과 status 필터",async({browser})=>{const stamp=Date.now(),rows=[{name:`QA-A-${stamp}`,company:`QA-COMP-${stamp}`,status:"received"},{name:`QA-B-${stamp}`,company:`QA-COMP-${stamp}`,status:"reviewing"},{name:`QA-C-${stamp}`,company:"OTHER",status:"accepted"}].map((x,i)=>({...x,cohort_id:COHORT,title:"대표",phone:`010-0000-000${i}`,email:`qa-adm002-${stamp}-${i}@example.com`,motivation:"QA"}));const seeded=await admin().from("applications").insert(rows).select("id");const c=await adminCtx(browser);try{const p=await c.newPage();await p.goto("/admin/applications",{waitUntil:"networkidle"});await p.getByPlaceholder(/이름·회사/).fill(`QA-COMP-${stamp}`);await expect(p.getByText(rows[0].name,{exact:true})).toBeVisible();await expect(p.getByText(rows[1].name,{exact:true})).toBeVisible();await expect(p.getByText(rows[2].name,{exact:true})).toHaveCount(0);await p.getByPlaceholder(/이름·회사/).fill("");await p.getByText(/^검토\s*\d+$/).click();await expect(p.getByText(rows[1].name,{exact:true})).toBeVisible();await expect(p.getByText(rows[0].name,{exact:true})).toHaveCount(0);}finally{await admin().from("applications").delete().in("id",(seeded.data??[]).map(r=>r.id));await c.close();}});
 test("ADM-003 received→reviewing→accepted DB·reload",async({browser})=>{const marker=`QA-ADM003-${Date.now()}`;const row=await admin().from("applications").insert({cohort_id:COHORT,name:marker,company:"QA",title:"대표",phone:"010-0000-0000",email:`${Date.now()}@example.com`,motivation:"QA",status:"received"}).select("id").single();const c=await adminCtx(browser);try{const p=await c.newPage();await p.goto("/admin/applications",{waitUntil:"networkidle"});const tr=p.locator("tr",{hasText:marker});await tr.getByRole("button",{name:"검토"}).click();await expect.poll(async()=> (await admin().from("applications").select("status").eq("id",row.data!.id).single()).data?.status).toBe("reviewing");await tr.getByRole("button",{name:"합격"}).click();await expect.poll(async()=> (await admin().from("applications").select("status").eq("id",row.data!.id).single()).data?.status).toBe("accepted");await p.reload({waitUntil:"networkidle"});await expect(p.locator("tr",{hasText:marker}).getByText("합격",{exact:true})).toBeVisible();}finally{await admin().from("applications").delete().eq("id",row.data!.id);await c.close();}});
 test("ADM-004 accepted 처리 invite·invoice·outbox 멱등",async({browser})=>{test.fail(true,"문서 known_gap: accepted 후 invite/invoice/outbox orchestration 없음");const c=await adminCtx(browser);try{const p=await c.newPage();await p.goto("/admin/applications",{waitUntil:"networkidle"});expect(await p.getByText(/초대 링크 생성 완료|인보이스 발행 완료/).count()).toBeGreaterThan(0);}finally{await c.close();}});
 test("ADM-007 세션 drag reorder DB·reload",async({browser})=>{const rows=[await seedSession(`QA-C-${Date.now()}`,-300),await seedSession(`QA-A-${Date.now()}`,-299),await seedSession(`QA-B-${Date.now()}`,-298)];const c=await adminCtx(browser);try{const p=await c.newPage();await p.goto("/admin/curriculum",{waitUntil:"networkidle"});const a=p.getByRole("button",{name:new RegExp(rows[1].title)}),b=p.getByRole("button",{name:new RegExp(rows[2].title)});await b.dragTo(a);await expect.poll(async()=>{const r=await admin().from("sessions").select("id,sort_order").in("id",rows.map(x=>x.id)).order("sort_order");return r.data?.map(x=>x.id);}).toEqual([rows[0].id,rows[2].id,rows[1].id]);await p.reload({waitUntil:"networkidle"});const text=await p.locator("main").innerText();expect(text.indexOf(rows[2].title)).toBeLessThan(text.indexOf(rows[1].title));}finally{for(const r of rows)await cleanSession(r.id);await c.close();}});
 test("ADM-008 미리보기 draft 표시·DB 무변경",async({browser})=>{const s=await seedSession(`QA-ADM008-${Date.now()}`,-400),draft=`DRAFT-${Date.now()}`;const c=await adminCtx(browser);try{const p=await c.newPage();await p.goto("/admin/curriculum",{waitUntil:"networkidle"});await p.locator("main input").first().fill(draft);await p.getByRole("button",{name:"미리보기"}).click();await expect(p.getByRole("heading",{name:draft})).toBeVisible();expect((await admin().from("sessions").select("title").eq("id",s.id).single()).data?.title).toBe(s.title);await p.getByRole("button",{name:"닫기"}).click();}finally{await cleanSession(s.id);await c.close();}});
 test("ADM-009 영상 연결→교체→제거 단일행",async({browser})=>{const s=await seedSession(`QA-ADM009-${Date.now()}`,-500),c=await adminCtx(browser);try{const p=await c.newPage();await p.goto("/admin/curriculum",{waitUntil:"networkidle"});const title=p.getByPlaceholder(/영상 제목/),url=p.getByPlaceholder(/youtu.be/);await title.fill("QA 영상");await url.fill("https://youtu.be/dQw4w9WgXcQ");await p.getByRole("button",{name:"연결"}).click();await expect.poll(async()=> (await admin().from("videos").select("google_drive_url").eq("session_id",s.id)).data).toHaveLength(1);await url.fill("https://example.com/qa.mp4");await p.getByRole("button",{name:"연결"}).click();await expect.poll(async()=> (await admin().from("videos").select("google_drive_url").eq("session_id",s.id).single()).data?.google_drive_url).toBe("https://example.com/qa.mp4");await url.fill("");await p.getByRole("button",{name:"연결"}).click();await expect.poll(async()=> (await admin().from("videos").select("id").eq("session_id",s.id)).data).toEqual([]);}finally{await cleanSession(s.id);await c.close();}});
 test("ADM-011 콘텐츠 작성·발행·수정·삭제와 trends",async({browser})=>{const title=`QA-ADM011-${Date.now()}`,edited=`${title}-EDIT`,c=await adminCtx(browser);try{const p=await c.newPage();await p.goto("/admin/contents",{waitUntil:"networkidle"});await p.getByRole("button",{name:"새 글 작성"}).click();await p.getByPlaceholder("제목").fill(title);await p.getByLabel("게시판").selectOption("ai_trend");await p.getByLabel("공개 범위").selectOption("public");await p.getByPlaceholder(/요약/).fill("QA 요약");await p.getByRole("button",{name:"저장",exact:true}).click();await expect(p.getByText(title,{exact:true})).toBeVisible();const row=await admin().from("posts").select("id,published_at").eq("title",title).single();expect(row.data?.published_at).toBeTruthy();const trends=await c.newPage();await trends.goto("/trends",{waitUntil:"networkidle"});await expect(trends.getByText(title,{exact:true})).toBeVisible();await p.getByText(title,{exact:true}).locator("xpath=ancestor::div[contains(@class,'rounded')][1]").getByRole("button",{name:/편집/}).click();await p.getByPlaceholder("제목").fill(edited);await p.getByRole("button",{name:"저장",exact:true}).click();await expect.poll(async()=> (await admin().from("posts").select("title").eq("id",row.data!.id).single()).data?.title).toBe(edited);await p.getByText(edited,{exact:true}).locator("xpath=ancestor::div[contains(@class,'rounded')][1]").getByRole("button",{name:/삭제/}).click();await expect.poll(async()=> (await admin().from("posts").select("id").eq("id",row.data!.id)).data).toEqual([]);}finally{await admin().from("posts").delete().in("title",[title,edited]);await c.close();}});
 for(const g of [["ADM-013","/admin/users",/회원 관리/],["ADM-014","/admin/version-packs",/Version Pack 복제/],["ADM-015","/admin/permissions",/권한 동기화/],["ADM-016","/login",/OTP|인증 코드/]] as const)test(`${g[0]} known-gap 계약`,async({browser})=>{test.fail(true,"문서 known_gap: 관리자 기능 미구현");const c=await adminCtx(browser);try{const p=await c.newPage();await p.goto(g[1],{waitUntil:"networkidle"});expect(await p.getByText(g[2]).count()).toBeGreaterThan(0);}finally{await c.close();}});
});
