import { expect, test, chromium, webkit, type Browser, type Page } from "@playwright/test";
import fs from "node:fs"; import path from "node:path";
import { admin, anon, assertMutationTarget, clientAs, userId, ANON_KEY, SUPABASE_URL } from "../lib/supa.mjs";
import { ensureStorageState } from "../fixtures/accounts";
const COHORT="00000000-0000-0000-0000-0000000000c1",SESSION="ed04829b-148e-4ae8-8462-cf80b41666db";
async function authCtx(browser:Browser,who:"student"|"admin"){return browser.newContext({storageState:await ensureStorageState(browser,who)});}

test.describe("security and NFR acceptance",()=>{
 test("SEC-001 모든 업무 테이블 RLS enable 정적 계약",async()=>{const dir=path.resolve(process.cwd(),"../ai4ceo/supabase/migrations");const sql=fs.readdirSync(dir).filter(f=>f.endsWith(".sql")).map(f=>fs.readFileSync(path.join(dir,f),"utf8")).join("\n");const tables=[...sql.matchAll(/create table if not exists\s+(?:public\.)?([a-z_]+)/gi)].map(m=>m[1]);const serviceOnly=new Set<string>();for(const table of new Set(tables)){const enabled=new RegExp(`alter table(?: if exists)? (?:public\\.)?${table} enable row level security`,`i`).test(sql)||new RegExp(`foreach t in array array\\[[\\s\\S]*'${table}'`,`i`).test(sql);expect(enabled||serviceOnly.has(table),`${table} RLS`).toBeTruthy();}});
 test("SEC-002 anon applications insert만 허용",async()=>{assertMutationTarget();const email=`qa-sec002-${Date.now()}@example.com`;try{const a=anon();const ins=await a.from("applications").insert({cohort_id:COHORT,name:"SEC002",company:"QA",title:"대표",phone:"010-0000-0000",email,motivation:"QA"});expect(ins.error).toBeNull();const svc=await admin().from("applications").select("id").eq("email",email).single();expect(svc.data?.id).toBeTruthy();expect((await a.from("applications").select("*").eq("email",email)).data).toEqual([]);expect((await a.from("applications").update({name:"HACK"}).eq("email",email).select("id")).data).toEqual([]);expect((await a.from("applications").delete().eq("email",email).select("id")).data).toEqual([]);}finally{await admin().from("applications").delete().eq("email",email);}});
 test("SEC-006 비수강생 cohort Q&A 조회·삽입 차단",async()=>{const q=await admin().from("session_questions").insert({session_id:SESSION,cohort_id:COHORT,author_id:await userId("student"),author_name:"QA",body:"SECRET-QA"}).select("id").single();try{const other=await clientAs("applicant");expect((await other.from("session_questions").select("*").eq("id",q.data!.id)).data).toEqual([]);const ins=await other.from("session_questions").insert({session_id:SESSION,cohort_id:COHORT,author_id:await userId("applicant"),body:"HACK"}).select("id");expect(ins.error).not.toBeNull();}finally{await admin().from("session_questions").delete().eq("id",q.data!.id);}});
 test("SEC-007 applicant 영상·자료 URL 차단",async()=>{const mat=await admin().from("materials").insert({session_id:SESSION,title:"SEC007",file_path:"https://secret.invalid/mat"}).select("id").single();const vid=await admin().from("videos").insert({session_id:SESSION,title:"SEC007",google_drive_url:"https://secret.invalid/video",visibility:"cohort_readonly"}).select("id").single();try{const other=await clientAs("applicant");expect((await other.from("materials").select("*").eq("id",mat.data!.id)).data).toEqual([]);expect((await other.from("videos").select("*").eq("id",vid.data!.id)).data).toEqual([]);}finally{await admin().from("materials").delete().eq("id",mat.data!.id);await admin().from("videos").delete().eq("id",vid.data!.id);}});
 test("SEC-010 unlinked assistant delegated task 차단",async()=>{const id=(await admin().from("delegated_tasks").insert({ceo_user_id:await userId("student"),assistant_email:"qa.assistant@example.com",title:"SEC010"}).select("id").single()).data!.id;try{const unlinked=await clientAs("assistant");expect((await unlinked.from("delegated_tasks").select("id").eq("id",id)).data).toEqual([]);expect((await unlinked.from("delegated_tasks").update({status:"done"}).eq("id",id).select("id")).data).toEqual([]);}finally{await admin().from("delegated_tasks").delete().eq("id",id);}});
 test("SEC-011 타인 roadmap select/update 차단",async()=>{const uid=await userId("student");const row=await admin().from("roadmaps").upsert({user_id:uid,cohort_id:COHORT,diagnosis:"SECRET"},{onConflict:"user_id"}).select("id").single();try{const b=await clientAs("alumniMember");expect((await b.from("roadmaps").select("*").eq("id",row.data!.id)).data).toEqual([]);expect((await b.from("roadmaps").update({diagnosis:"HACK"}).eq("id",row.data!.id).select("id")).data).toEqual([]);}finally{await admin().from("roadmaps").delete().eq("id",row.data!.id);}});
 test("SEC-012 JS bundle·network에 server secret 이름 없음",async({page})=>{const urls=new Set<string>();page.on("response",r=>{if(/\.(?:js|map)(?:\?|$)/.test(r.url()))urls.add(r.url());});await page.goto("/",{waitUntil:"networkidle"});let text=await page.content();for(const url of urls){const r=await page.request.get(url);if(r.ok())text+=await r.text();}expect(text).not.toMatch(/SUPABASE_SERVICE_ROLE_KEY|SMTP_(?:PASS|PASSWORD)|TOSS_(?:SECRET|KEY)|POPBILL_(?:SECRET|KEY)/i);});
 test("SEC-013 application rate limit 21회 후 429",async({page})=>{test.fail(true,"문서 known_gap: application rate limit/captcha 미구현");const stamp=Date.now(),statuses:number[]=[];try{for(let i=0;i<21;i++){const r=await page.request.post(`${SUPABASE_URL}/rest/v1/applications`,{headers:{apikey:ANON_KEY,Authorization:`Bearer ${ANON_KEY}`,Prefer:"return=minimal"},data:{cohort_id:COHORT,name:"RATE",company:"QA",title:"대표",phone:"010-0000-0000",email:`qa-rate-${stamp}-${i}@example.com`,motivation:"QA"}});statuses.push(r.status());}expect(statuses).toContain(429);}finally{await admin().from("applications").delete().like("email",`qa-rate-${stamp}-%`);}});
 test("SEC-014 opt-in false PII가 public HTML/RSC에 없음",async({page})=>{const marker=`PRIVATE-${Date.now()}`,b=await admin().from("builds").insert({user_id:await userId("student"),cohort_id:COHORT,title:marker,description:marker,visibility:"cohort"}).select("id").single();try{for(const route of ["/","/program","/trends"]){await page.goto(route,{waitUntil:"networkidle"});expect(await page.content()).not.toContain(marker);}}finally{await admin().from("builds").delete().eq("id",b.data!.id);}});

 test("NFR-001 public 3 route 3회 median <2.5s·failed resource 0",async({browser})=>{for(const route of ["/","/program","/apply"]){const samples:number[]=[];for(let i=0;i<3;i++){const c=await browser.newContext();const p=await c.newPage();const failed:string[]=[];p.on("requestfailed",r=>{const url=r.url();const reason=r.failure()?.errorText??"";if(!url.includes("/.well-known/vercel/jwe")&&!reason.includes("ERR_ABORTED"))failed.push(url);});const start=Date.now();await p.goto(route,{waitUntil:"networkidle"});samples.push(Date.now()-start);expect(failed).toEqual([]);await c.close();}samples.sort((a,b)=>a-b);expect(samples[1],`${route} median`).toBeLessThan(2500);}});
 test("NFR-002 portal route transition median/p95",async({browser})=>{const c=await authCtx(browser,"student");try{const p=await c.newPage();await p.goto("/portal/cohort",{waitUntil:"networkidle"});const routes=["/portal/sessions/s1","/portal/builds","/portal/tasks","/portal/roadmap","/portal/cohort"];const times:number[]=[];for(const route of routes){const link=p.locator(`a[href="${route}"]:visible`).first();await expect(link).toBeVisible();const t=Date.now();await Promise.all([p.waitForURL(url=>url.pathname===route),link.click()]);times.push(Date.now()-t);}const sorted=[...times].sort((a,b)=>a-b),detail=routes.map((route,i)=>`${route}=${times[i]}ms`).join(", ");expect(sorted[2],detail).toBeLessThan(1000);expect(sorted[4],detail).toBeLessThan(2000);}finally{await c.close();}});
 test("NFR-003 주요 route 기본 접근성·keyboard",async({browser})=>{const c=await authCtx(browser,"student");try{for(const route of ["/","/program","/apply","/login","/portal/cohort","/portal/sessions","/portal/files","/portal/builds","/portal/tasks","/portal/roadmap"]){const p=await c.newPage();await p.goto(route,{waitUntil:"networkidle"});expect(await p.locator('button:not([aria-label])').evaluateAll(btns=>btns.filter(b=>!(b.textContent||'').trim()).length)).toBe(0);expect(await p.locator('input').evaluateAll(xs=>xs.filter(x=>!x.getAttribute('aria-label')&&!x.getAttribute('placeholder')&&!x.id).length)).toBe(0);const alreadyFocused=await p.evaluate(()=>document.activeElement!==document.body);await p.keyboard.press(alreadyFocused?"Shift+Tab":"Tab");expect(await p.evaluate(()=>document.activeElement!==document.body),`${route} -> ${p.url()}`).toBeTruthy();await p.close();}}finally{await c.close();}});
 test("NFR-004 3 viewport 주요 route overflow·touch target",async({browser})=>{for(const viewport of [{width:390,height:844},{width:768,height:1024},{width:1440,height:900}]){const c=await browser.newContext({viewport,storageState:await ensureStorageState(browser,"student")});const p=await c.newPage();await p.goto("/portal/cohort",{waitUntil:"networkidle"});expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();if(viewport.width===390){const sizes=await p.locator('button:visible,a:visible').evaluateAll(xs=>xs.slice(0,20).map(x=>{const r=x.getBoundingClientRect();return Math.min(r.width,r.height)}));expect(Math.min(...sizes)).toBeGreaterThanOrEqual(44);}await c.close();}});
 test("NFR-005 Chromium·WebKit P0 public journey",async()=>{for(const type of [chromium,webkit]){const b=await type.launch({headless:false});try{const p=await b.newPage();const errors:string[]=[];p.on("console",m=>{if(m.type()==="error"&&!/Failed to fetch RSC payload.*Falling back to browser navigation/.test(m.text()))errors.push(m.text());});for(const route of ["/","/program","/apply"]){await p.goto(`${process.env.TEST_BASE_URL}${route}`,{waitUntil:"domcontentloaded"});await expect(p.locator("body")).not.toBeEmpty();}expect(errors).toEqual([]);}finally{await b.close();}}});
 test("NFR-006 PWA manifest·SW·offline shell",async({page})=>{test.fail(true,"문서 known_gap: PWA 미구현");const m=await page.request.get("/manifest.webmanifest");expect(m.status()).toBe(200);const manifest=await m.json();expect(manifest).toMatchObject({name:expect.any(String),start_url:expect.any(String)});await page.goto("/",{waitUntil:"networkidle"});expect(await page.evaluate(()=>navigator.serviceWorker?.controller!=null)).toBeTruthy();});
 test("NFR-007 지원 폼 개인정보 동의·6개월",async({page})=>{test.fail(true,"문서 known_gap: privacy consent 미구현");await page.goto("/apply",{waitUntil:"networkidle"});await expect(page.getByRole("link",{name:/개인정보처리방침/})).toBeVisible();await expect(page.getByText(/6개월/)).toBeVisible();await expect(page.getByRole("checkbox",{name:/필수.*동의/})).toBeVisible();});
 test("NFR-008 사용자 문자열 translation key",async()=>{test.fail(true,"문서 known_gap: i18n 체계 미구현");const root=path.resolve(process.cwd(),"../ai4ceo");expect(fs.existsSync(path.join(root,"messages","ko.json"))||fs.existsSync(path.join(root,"locales","ko.json"))).toBeTruthy();});
});
