import { expect, test, type Browser } from "@playwright/test";
import { admin, assertMutationTarget, clientAs, userId, ACCOUNT_EMAILS } from "../lib/supa.mjs";
import { ensureStorageState, type AccountKey } from "../fixtures/accounts";

const COHORT="00000000-0000-0000-0000-0000000000c1";
async function ctx(browser:Browser, who:AccountKey){return browser.newContext({storageState:await ensureStorageState(browser,who)});}
async function seedBuild(tag:string, extra:Record<string,unknown>={}){const uid=await userId("student");const r=await admin().from("builds").insert({user_id:uid,cohort_id:COHORT,title:tag,description:"QA 설명",repo_url:"https://github.com/qa/repo",visibility:"cohort",apply_status:"none",...extra}).select("*").single();if(r.error)throw r.error;return r.data;}
async function cleanBuild(id:string){await admin().from("roadmaps").update({build_ids:[]}).contains("build_ids",[id]);await admin().from("builds").delete().eq("id",id);}
async function linkAssistantToStudent(){
  const row=await admin().from("assistant_links").upsert({
    assistant_id:await userId("assistant"),
    student_id:await userId("student"),
    cohort_id:COHORT,
  },{onConflict:"assistant_id,student_id,cohort_id"}).select("id").single();
  if(row.error)throw row.error;
  return row.data.id as string;
}

test.describe("v3 workflows acceptance",()=>{
 test("TASK-001 새 위임 DB·목록 최상단",async({browser})=>{assertMutationTarget();const marker=`QA-TASK001-${Date.now()}`;const c=await ctx(browser,"student");try{const p=await c.newPage();await p.goto("/portal/tasks",{waitUntil:"networkidle"});await p.getByPlaceholder(/할 일 제목/).fill(marker);await p.getByPlaceholder("assistant 이메일").fill(ACCOUNT_EMAILS.assistant);await p.getByRole("combobox",{name:"유형"}).selectOption("assignment");await p.getByPlaceholder(/메모/).fill("QA 메모");await p.getByRole("button",{name:"위임하기"}).click();await expect(p.getByText(marker,{exact:true})).toBeVisible();const row=(await admin().from("delegated_tasks").select("*").eq("title",marker).single()).data;expect(row).toMatchObject({ceo_user_id:await userId("student"),assistant_email:ACCOUNT_EMAILS.assistant,note:"QA 메모",source_type:"assignment",status:"pending"});}finally{await admin().from("delegated_tasks").delete().eq("title",marker);await c.close();}});
 test("TASK-002 assistant 상태 pending→in_progress→done 영속",async({browser})=>{const linkId=await linkAssistantToStudent();const marker=`QA-TASK002-${Date.now()}`;const seeded=await admin().from("delegated_tasks").insert({ceo_user_id:await userId("student"),assistant_email:ACCOUNT_EMAILS.assistant,title:marker,status:"pending"}).select("id").single();const c=await ctx(browser,"assistant");try{const p=await c.newPage();await p.goto("/portal/tasks",{waitUntil:"networkidle"});const card=p.locator("article, div.rounded-\\[15px\\]",{hasText:marker}).last();await card.getByRole("button",{name:"진행 시작"}).click();await expect.poll(async()=> (await admin().from("delegated_tasks").select("status").eq("id",seeded.data!.id).single()).data?.status).toBe("in_progress");await card.getByRole("button",{name:"완료 처리"}).click();await expect.poll(async()=> (await admin().from("delegated_tasks").select("status").eq("id",seeded.data!.id).single()).data?.status).toBe("done");await p.reload({waitUntil:"networkidle"});await expect(p.locator("body")).toContainText(marker);await expect(p.locator("body")).toContainText("완료");}finally{await admin().from("delegated_tasks").delete().eq("id",seeded.data!.id);await admin().from("assistant_links").delete().eq("id",linkId);await c.close();}});
 test("TASK-003 연결 assistant만 task 조회·수정",async()=>{const linkId=await linkAssistantToStudent();const id=(await admin().from("delegated_tasks").insert({ceo_user_id:await userId("student"),assistant_email:ACCOUNT_EMAILS.assistant,title:`QA-TASK003-${Date.now()}`}).select("id").single()).data!.id;try{const assistant=await clientAs("assistant"),other=await clientAs("alumniMember");expect((await assistant.from("delegated_tasks").select("id").eq("id",id)).data).toHaveLength(1);expect((await assistant.from("delegated_tasks").update({status:"in_progress"}).eq("id",id).select("id")).data).toHaveLength(1);expect((await other.from("delegated_tasks").select("id").eq("id",id)).data).toEqual([]);expect((await other.from("delegated_tasks").update({status:"done"}).eq("id",id).select("id")).data).toEqual([]);}finally{await admin().from("delegated_tasks").delete().eq("id",id);await admin().from("assistant_links").delete().eq("id",linkId);}});
 test("TASK-004 빈 제목·invalid assistant validation",async({browser})=>{const c=await ctx(browser,"student");try{const p=await c.newPage();await p.goto("/portal/tasks",{waitUntil:"networkidle"});await p.getByRole("button",{name:"위임하기"}).click();await expect(p.getByText("제목을 입력해 주세요.")).toBeVisible();await p.getByPlaceholder(/할 일 제목/).fill("QA");await p.getByPlaceholder("assistant 이메일").fill("bad");await p.getByRole("button",{name:"위임하기"}).click();await expect(p.getByText("assistant 이메일을 확인해 주세요.")).toBeVisible();}finally{await c.close();}});

 test("BUILD-001 결과물 등록 DB와 카드",async({browser})=>{const marker=`QA-BUILD001-${Date.now()}`;const c=await ctx(browser,"student");try{const p=await c.newPage();await p.goto("/portal/builds",{waitUntil:"networkidle"});await p.getByRole("button",{name:/결과물 등록/}).first().click();await p.getByPlaceholder("결과물 제목").fill(marker);await p.getByPlaceholder(/설명/).fill("설명");await p.getByPlaceholder(/레포/).fill("https://github.com/qa/build");await p.getByRole("button",{name:"등록하기"}).click();await expect(p.getByText(marker,{exact:true})).toBeVisible();expect((await admin().from("builds").select("user_id,cohort_id,description,repo_url,apply_status").eq("title",marker).single()).data).toMatchObject({user_id:await userId("student"),cohort_id:COHORT,description:"설명",repo_url:"https://github.com/qa/build",apply_status:"none"});}finally{const rows=await admin().from("builds").select("id").eq("title",marker);for(const r of rows.data??[])await cleanBuild(r.id);await c.close();}});
 for(const f of [{id:"BUILD-002",kind:"status"},{id:"BUILD-003",kind:"memo"},{id:"BUILD-004",kind:"visibility"}] as const)test(`${f.id} 결과물 ${f.kind} DB 영속`,async({browser})=>{const b=await seedBuild(`QA-${f.id}-${Date.now()}`);const c=await ctx(browser,"student");try{const p=await c.newPage();await p.goto("/portal/builds",{waitUntil:"networkidle"});await p.getByRole("button",{name:new RegExp(b.title)}).click();if(f.kind==="status"){for(const [label,value] of [["검토중","review"],["파일럿","pilot"],["적용완료","applied"]]){await p.getByText(label,{exact:true}).last().click();await expect.poll(async()=> (await admin().from("builds").select("apply_status").eq("id",b.id).single()).data?.apply_status).toBe(value);}}else if(f.kind==="memo"){const memo="  시간 30% 절감  ";await p.getByPlaceholder(/시간·비용/).fill(memo);await p.getByRole("button",{name:"저장",exact:true}).click();await expect.poll(async()=> (await admin().from("builds").select("effect_memo").eq("id",b.id).single()).data?.effect_memo).toBe(memo);await p.reload({waitUntil:"networkidle"});await p.getByRole("button",{name:new RegExp(b.title)}).click();await expect(p.getByPlaceholder(/시간·비용/)).toHaveValue(memo);}else{const sw=p.getByRole("switch");await sw.click();await expect(sw).toHaveAttribute("aria-checked","true");await expect.poll(async()=> (await admin().from("builds").select("visibility").eq("id",b.id).single()).data?.visibility).toBe("public");await sw.click();await expect.poll(async()=> (await admin().from("builds").select("visibility").eq("id",b.id).single()).data?.visibility).toBe("cohort");}}finally{await c.close();await cleanBuild(b.id);}});
 test("BUILD-005 다른 사용자의 cohort build 조회·수정 차단",async()=>{const b=await seedBuild(`QA-BUILD005-${Date.now()}`,{effect_memo:"SECRET"});try{const other=await clientAs("alumniMember");expect((await other.from("builds").select("*").eq("id",b.id)).data).toEqual([]);expect((await other.from("builds").update({effect_memo:"HACK"}).eq("id",b.id).select("id")).data).toEqual([]);}finally{await cleanBuild(b.id);}});

 test("ROAD-001 4단계 draft 자동저장 단일행",async({browser})=>{const uid=await userId("student");await admin().from("roadmaps").delete().eq("user_id",uid);const c=await ctx(browser,"student");try{const p=await c.newPage();await p.goto("/portal/roadmap",{waitUntil:"networkidle"});const vals=["진단 QA","우선 QA","90일 QA","확산 QA"];const boxes=p.locator("textarea");for(let i=0;i<4;i++)await boxes.nth(i).fill(vals[i]);await expect(p.getByText(/자동 저장됨/)).toBeVisible();await expect.poll(async()=> (await admin().from("roadmaps").select("*").eq("user_id",uid)).data).toHaveLength(1);expect((await admin().from("roadmaps").select("diagnosis,priorities,plan_90d,expansion,status").eq("user_id",uid).single()).data).toMatchObject({diagnosis:vals[0],priorities:vals[1],plan_90d:vals[2],expansion:vals[3],status:"draft"});}finally{await admin().from("roadmaps").delete().eq("user_id",uid);await c.close();}});
 test("ROAD-002 본인 Build 하나 연결",async({browser})=>{const uid=await userId("student"),b=await seedBuild(`QA-ROAD002-${Date.now()}`);await admin().from("roadmaps").delete().eq("user_id",uid);const c=await ctx(browser,"student");try{const p=await c.newPage();await p.goto("/portal/roadmap",{waitUntil:"networkidle"});await p.getByText("+ Build 근거 첨부").click();await p.getByText(b.title,{exact:true}).click();await expect.poll(async()=> (await admin().from("roadmaps").select("build_ids").eq("user_id",uid).single()).data?.build_ids).toEqual([b.id]);}finally{await admin().from("roadmaps").delete().eq("user_id",uid);await c.close();await cleanBuild(b.id);}});
 test("ROAD-003 final과 발표 모드 4단계",async({browser})=>{const uid=await userId("student");await admin().from("roadmaps").upsert({user_id:uid,cohort_id:COHORT,status:"draft",diagnosis:"D",priorities:"P",plan_90d:"90",expansion:"E"},{onConflict:"user_id"});const c=await ctx(browser,"student");try{const p=await c.newPage();await p.goto("/portal/roadmap",{waitUntil:"networkidle"});await p.getByRole("button",{name:"발표본"}).click();await expect.poll(async()=> (await admin().from("roadmaps").select("status").eq("user_id",uid).single()).data?.status).toBe("final");await p.getByRole("button",{name:"발표 모드"}).click();await expect(p.getByText("STEP 1 / 4")).toBeVisible();for(let i=0;i<3;i++)await p.getByRole("button",{name:"다음 슬라이드"}).click();await expect(p.getByText("STEP 4 / 4")).toBeVisible();}finally{await admin().from("roadmaps").delete().eq("user_id",uid);await c.close();}});
 test("ROAD-004 타인 roadmap 조회·수정 차단",async()=>{const uid=await userId("student");const row=await admin().from("roadmaps").upsert({user_id:uid,cohort_id:COHORT,diagnosis:"SECRET"},{onConflict:"user_id"}).select("id").single();try{const other=await clientAs("alumniMember");expect((await other.from("roadmaps").select("*").eq("id",row.data!.id)).data).toEqual([]);expect((await other.from("roadmaps").update({diagnosis:"HACK"}).eq("id",row.data!.id).select("id")).data).toEqual([]);}finally{await admin().from("roadmaps").delete().eq("id",row.data!.id);}});

 async function seedPosts(tag:string){const rows=[15,16,17].map(n=>({board:"brief",title:`${tag}-${n}`,external_url:`https://example.com/${n}`,category:`${n}기`,tags:[`${n}기`],audience:"alumni"}));const r=await admin().from("posts").insert(rows).select("id,title");if(r.error)throw r.error;return r.data!;}
 test("ARCH-001 active member 기수 필터·읽기",async({browser})=>{const tag=`QA-ARCH001-${Date.now()}`,rows=await seedPosts(tag),c=await ctx(browser,"alumniMember");try{const p=await c.newPage();await p.goto("/alumni/archive",{waitUntil:"networkidle"});await expect(p.getByText("멤버십 이용 중",{exact:true}).first()).toBeVisible();await p.getByText("15기",{exact:true}).first().click();await expect(p.getByText(`${tag}-15`,{exact:true})).toBeVisible();await expect(p.getByText(`${tag}-16`,{exact:true})).toHaveCount(0);expect(await p.getByRole("link",{name:"읽기"}).count()).toBeGreaterThan(0);}finally{await admin().from("posts").delete().in("id",rows.map(r=>r.id));await c.close();}});
 test("ARCH-002 expired는 전체 item 잠금",async({browser})=>{const tag=`QA-ARCH002-${Date.now()}`,rows=await seedPosts(tag),c=await ctx(browser,"alumniExpired");try{const p=await c.newPage();await p.goto("/alumni/archive",{waitUntil:"networkidle"});await expect(p.getByText("멤버십 만료",{exact:true})).toBeVisible();await expect(p.getByRole("link",{name:"멤버십 갱신"})).toBeVisible();for(const n of [15,16,17]){const card=p.locator("article,div.rounded-\\[15px\\]",{hasText:`${tag}-${n}`});await expect(card.getByText(/갱신 후 이용 가능/)).toBeVisible();await expect(card.getByRole("link",{name:"읽기"})).toHaveCount(0);}const expired=await clientAs("alumniExpired");const locked=await expired.rpc("list_locked_archive_metadata");expect(locked.error).toBeNull();const seeded=(locked.data??[]).filter((r:any)=>String(r.title).startsWith(tag));expect(seeded).toHaveLength(3);for(const row of seeded)expect(Object.keys(row).sort()).toEqual(["category","cohort_id","id","published_at","tags","title"]);for(const who of ["applicant","student"] as AccountKey[])expect((await (await clientAs(who)).rpc("list_locked_archive_metadata")).data).toEqual([]);}finally{await admin().from("posts").delete().in("id",rows.map(r=>r.id));await c.close();}});
 test("ARCH-003 post 0건 empty state",async({browser})=>{const existing=await admin().from("posts").select("*").in("board",["brief","ai_trend"]);await admin().from("posts").delete().in("board",["brief","ai_trend"]);const c=await ctx(browser,"alumniMember");try{const p=await c.newPage();await p.goto("/alumni/archive",{waitUntil:"networkidle"});await expect(p.getByText(/아직 공개된 아카이브 콘텐츠가 없습니다/)).toBeVisible();}finally{if(existing.data?.length)await admin().from("posts").insert(existing.data);await c.close();}});
 test("ARCH-004 alumni 전용 post는 active member/admin만",async()=>{const id=(await admin().from("posts").insert({board:"brief",title:`QA-ARCH004-${Date.now()}`,audience:"alumni"}).select("id").single()).data!.id;try{for(const who of ["alumniMember","admin"] as AccountKey[])expect((await (await clientAs(who)).from("posts").select("id").eq("id",id)).data).toHaveLength(1);for(const who of ["applicant","student","alumniExpired"] as AccountKey[])expect((await (await clientAs(who)).from("posts").select("id").eq("id",id)).data).toEqual([]);}finally{await admin().from("posts").delete().eq("id",id);}});
});
